### ISSUE TITLE
Model Visualization with Chitra

### ISSUE THREAD

**Issue by aniketmaurya** [keisen/tf-keras-vis#37]
Check out [Chitra](https://chitra.aniketmaurya.ml/#Model-Visualization) which uses `tf-keras-vis` for GradCAM visualization.

You can train CNNs in few lines and also interpret your model with InterpretModel class.

<img width="833" alt="Screenshot 2020-11-25 at 2 15 41 AM" src="https://user-images.githubusercontent.com/21018714/100149404-1f634800-2ec4-11eb-8cec-d1ae378dfea6.png">

**Comment by keisen** [comment]
Hi, @aniketmaurya .
Thank you for letting us know your great works!
I'm glad that you use `tf-keras-vis` in it.

I'm going to close this issue, but whenever please feel free to ask me if you face any questions or problems.

p.s.,

May I introduce Chitra on README.md of tf-keras-vis?

**Comment by aniketmaurya** [comment]
Thank you @keisen .
tf-keras-vis is a really great library for model explainability. I would be grateful if you can introduce Chitra on the README of tf-keras-vis.
