### ISSUE TITLE
Is Vanilla Saliency Implemented? I could see only smooth-grad in saliency.py

### ISSUE THREAD

**Issue by man0007** [keisen/tf-keras-vis#55]

**Comment by bersbersbers** [comment]
Yes. https://www.github.com/keisen/tf-keras-vis/tree/master/README.md

**Comment by bersbersbers** [comment]
Your comment implies that you are not aware of the relationship between Vanilla saliency and SmoothGrad, so you probably haven't read the relevant literature. You should - blindly applying any CNN visualization method is not what interpretable machine learning is about. Links are in the readme as well.

**Comment by keisen** [comment]
@man0007 , In default (that's when `smooth_samples=0`) ,the `Saliency#__call__()` works as Vanilla Saliency.
When setting 1 or more to `smooth_sample`, it will work as Smooth Grad.

https://github.com/keisen/tf-keras-vis/blob/ddd951396f16e7f5b7a0e8619f43f99c599628fb/tf_keras_vis/saliency.py#L9-L13

Please see [this example notebook](https://github.com/keisen/tf-keras-vis/blob/master/examples/attentions.ipynb) for details!

I would be glad if it helped you out.
Although I'm going to close this issue, please feel free to re-open this issue when you have any question or face any problem.
Thanks!
