### ISSUE TITLE
problem after updating to tensorflow 2.5 and keras 2.4 - Expected `model` argument

### ISSUE THREAD

**Issue by kinaikan** [keisen/tf-keras-vis#72]
Hi,

just after updating tensorflow to 2.5.0 and keras to 2.4.3, I can not use tf_keras_vis anymore, when I pass my model to functions I get 
`('Expected `model` argument to be a `Model` instance, got ', <keras.engine.functional.Functional object at 0x00000230BFDB2AC0>)`
I also upgraded the tf-keras-vis package, but still I get the same error.

did anyone else face the same thing?

**Comment by keisen** [comment]
Are you importing `keras` package like below?

```python
import keras

model = keras.Model(...
```

Tensorflow2.5 doesn't support for keras package. Instead, `keras` module are provided as `tensorflow.keras`.
So you should use it like below.

```python
import tensorflow as tf

model = tf.keras.Model(...
```

Thanks!

**Comment by keisen** [comment]
Hi, @kinaikan .
Although I believe that the problem was resolved, do you have any other questions or problems?
I'm going to close this issue.
When you're facing any problem, please feel free to re-open this issue.

Finally, if you like tf-keras-vis, please star this repository.
Thanks!

**Comment by kinaikan** [comment]
Hi, @keisen .

sry I was busy last week. I will check your suggestion this weekend and report back to you.

Thanks.
