### ISSUE TITLE
Add a Citation widget to the repo

### ISSUE THREAD

**Issue by ianbgroves** [keisen/tf-keras-vis#81]
Hello,

I would like to cite this repo in an academic paper. I could not find any citation guidance on the repo or the docs. However, Github has inbuilt functionality for adding the relevant information. Would it be possible for a .cff file to be added?
[Add a .cff file](https://citation-file-format.github.io/)

**Comment by keisen** [comment]
Thank you for your advice! I'm going to add a .cff file from now.

Thanks!
