### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by bersbersbers** [keisen/tf-keras-vis#9]
```
user@host:~/pip_patches> python --version
Python 3.8.2
user@host:~/pip_patches> pip install tf-keras-vis==0.2.2
ERROR: Could not find a version that satisfies the requirement tf-keras-vis==0.2.2 (from versions: 0.0.1, 0.1.0)
ERROR: No matching distribution found for tf-keras-vis==0.2.2
```

**Comment by keisen** [comment]
Thank you for your reporting.
I'll deal with this issue when TF supported Python 3.8+.

https://www.tensorflow.org/install#install-tensorflow-2

**Comment by bersbersbers** [comment]
Which is now :)

> Windows/Linux binaries for py3.8 are available

https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0

**Comment by keisen** [comment]
Thank you for letting me know! I'll deal with it in PR/#7.

**Comment by bersbersbers** [comment]
```
> pip install tf-keras-vis==0.2.4
ERROR: Could not find a version that satisfies the requirement tf-keras-vis==0.2.4 (from versions: 0.0.1, 0.1.0)
ERROR: No matching distribution found for tf-keras-vis==0.2.4
```

PyPI says `Requires: Python >=3.5, <=3.8` - could it be that that excludes Python 3.8.2?

**Comment by keisen** [comment]
Thank you for letting me know that! I didn't realize it.
For now, I applied a patch to `setup.py` and uploaded v0.2.5 to PyPI.
Could you please try it again.

**Comment by bersbersbers** [comment]
> Successfully installed tf-keras-vis-0.2.5
Beautiful, thank you!
